services:
  cleanarchitecturecqrs.api:
    image: ${DOCKER_REGISTRY-}cleanarchitecturecqrsapi
    build:
      context: .
      dockerfile: CleanArchitectureCQRS/Dockerfile
    expose:
      - "8080"
    environment:
     - ASPNETCORE_ENVIRONMENT=Production
     - ASPNETCORE_URLS=http://+:8080
     - DB_HOST=db
    depends_on:
     - db
    
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - cleanarchitecturecqrs.api

  redis:
    image: redis:8.4-rc1-alpine3.22
    ports:
     - "6379:6379"
    volumes:
     - redis_data:/data

  # db:
  #   image: "postgres:latest"
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin 
  #     POSTGRES_DB: DB_HR
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - pgdata:/var/lib/postgresql

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SenhaForte!120276
      - MSSQL_PID=Developer
      - TrustServerCertificate=True
    ports:
      - "6433:1433"
    volumes:
        - mssql_data:/var/opt/mssql

volumes:
  pgdata:
  mssql_data:
  redis_data:  